apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      defaultDatabase: university
      port: 9000
      server: clickhouse
      username: default
      protocol: native
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    isDefault: true
    editable: true